### ISSUE TITLE
KeyError: 'Unable to synchronously open object (component not found)' add_ngs_coverage.py

### ISSUE THREAD

**Issue by arslan9732** [weberlab-hhu/Helixer#112]
Hi,
I am running Helixer with [tuning-with-extrinsic-information](https://github.com/weberlab-hhu/Helixer/blob/main/docs/fine_tuning.md#tuning-with-extrinsic-information), I am facing following error while running [add_ngs_coverage.py](https://github.com/weberlab-hhu/Helixer/blob/main/helixer/evaluation/add_ngs_coverage.py).

```
Traceback (most recent call last):
  File "add_ngs_coverage.py", line 476, in main
    old_shape = h5['evaluation/' + NGS_COVERAGE_SETS[0]].shape
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/mnt/bin/helixer/env_v0.3.2/lib64/python3.8/site-packages/h5py/_hl/group.py", line 357, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 189, in h5py.h5o.open
KeyError: 'Unable to synchronously open object (component not found)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "add_ngs_coverage.py", line 581, in <module>
    main(args.species,
  File "add_ngs_coverage.py", line 485, in main
    add_empty_ngs_datasets(h5, nbams)
  File "add_ngs_coverage.py", line 285, in add_empty_ngs_datasets
    length = h5['data/X'].shape[0]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/mnt/bin/helixer/env_v0.3.2/lib64/python3.8/site-packages/h5py/_hl/group.py", line 357, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 189, in h5py.h5o.open
KeyError: 'Unable to synchronously open object (component not found)'
```

Please let me know how to resolve this error, or is this a bug?

**Comment by hjjansen** [comment]
I had an error with that script as well but haven't logged it so I'm not sure if it is the same error.
My error was solved by running it without multi-threading, so `--threads 1`.
Hope that will work for you.

**Comment by arslan9732** [comment]
@hjjansen 
Sorry, it also didn't work with `--threads 1`.

**Comment by hjjansen** [comment]
Then I'm afraid I can't help you any further as my python skills are somewhat limited ;-)

**Comment by alisandra** [comment]
Hi @arslan9732 , 

Thanks for your interest in Helixer and feedback on how it was going!

This error message is at least not expected. 

Some thoughts - 

Looking at the second error, where it fails to find ''data/X" in the h5 file, this probably indicates an issue with the input h5 file; especially if multi threading has already been turned off. You can check file contents with e.g. `h5ls <your-file.h5>` (from the `hdf5-tools` package) where you should see a variety of datasets under 'data' (look [here](https://github.com/weberlab-hhu/Helixer/blob/main/docs/h5_data.md) for more info), as well as a simple check that it is non-empty based on it's size (`ls -sh`). It might be worth scrutinizing the step(s) before that it/they completed successfully. 

Otherwise, the`add_ngs_coverage.py` script modifies the h5 file in place. So if a previous run did not complete for any reason, you'll want to regenerate (or hopefully utilize your backup of the helixer post converted back to h5 file) as mentioned [here](https://github.com/weberlab-hhu/Helixer/blob/main/docs/fine_tuning.md#add-aligned-reads-to-the-h5-file-as-coverage-tracks). 

If none of that helps, I'll be able to help more the more information you give me, in particular, current and previous commands, and the result of `h5ls <your-file.h5>`.

**Comment by arslan9732** [comment]
Hi @alisandra,
Thanks for your response.
I tried your mentioned suggestions, but the error is still there.
Here is the output of `h5ls`
```
$ h5ls predictions.h5
predictions              Dataset {1065054/Inf, 21384, 4}
predictions_phase        Dataset {1065054/Inf, 21384, 4}
``` 

Here are the previous commands:
```
fasta2h5.py --species my_species --h5-output-path genome.h5 --fasta-path genome.v1.fa

HybridModel.py --load-model-path /mnt/bin/helixer/models/land_plant/land_plant_v0.3_a_0080.h5 \
--test-data genome.h5 --overlap --val-test-batch-size 32 -v
```
then I run `add_ngs_coverage.py`

```
add_ngs_coverage.py --unstranded -s my_species  --h5-data predictions.h5  --dataset-prefix rnaseq  --bam SRR14354617.bam --threads 1
```

**Comment by alisandra** [comment]
Thanks for the additional info @arslan9732,

The coverage needs to be added to genome.h5, not predictions.h5

Let me know and reopen this issue in case that does not fix it.
